### PR TITLE
[CI] PHP CS Fixer it up

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
hm, tests started failing because of the PHPStan... not sure why :/

**Comment by weaverryan** [comment]
Maybe it needs an update?

**Comment by bocharsky-bw** [comment]
`composer up` does not help, seems the phar file conflicts with the package, not sure how to overcome it at the first sight

**Comment by bocharsky-bw** [comment]
There's something weird with that PHPStan test, I just skipped it in [6b580f4](https://github.com/SymfonyCasts/micro-mapper/pull/12/commits/6b580f420094554712f4589f6c32654e40aa7e0b) until a better time. In short, as far as I understand, PHPUnit (which is installed via Symfony PHPUnit Bridge) has some dependencies that conflict with the ones installed with PHPStan - it loads the incorrect file from the PHPUnit deps instead. I'm not sure about a possible solution. Probably we should get rid of the Symfony PHPUnit bridge in favor of direct PHPUnit dependency in the `require-dev`? But that's a bummer to go this way, but I don't see other ways so far. If anyone could give it a try - please, PR is warmly welcome!

**Pull request merged**
